name: tf_tutorial
dependencies:
  # Base
  - python=3.6.2
  # Visualisation
  - matplotlib=2.0.2
  # Analysis
  - scikit-learn=0.19.0
  - numpy=1.13.1
  # Reporting
  - pandas=0.20.3
  # TensorFlow
  - pip=9.0.1
  - pip:
    - tensorflow==1.3.0
